 pref("extensions.attachmentscanner.scan_nosource", true);
 pref("extensions.attachmentscanner.scan_duplicates", true);
 pref("extensions.attachmentscanner.scan_nonfiles", false);
 pref("extensions.attachmentscanner.remove_pubmed_entry", false);
 pref("extensions.attachmentscanner.monitor_attachments", true);
 pref("extensions.attachmentscanner.tag_nosource", "#nosource");
 pref("extensions.attachmentscanner.tag_broken", "#broken");
 pref("extensions.attachmentscanner.tag_duplicate", "#duplicate");
 pref("extensions.attachmentscanner.tag_nonfile", "#nonfile");
